[pytest]
log_cli = true
log_cli_level = INFO
addopts = -v -s
testpaths = tests
markers =
    integration: Integration tests
    schema: Schema validation tests
    statuscode: Status code validation tests
    contract: Contract tests